package exception.code;

public enum ErrorCode {

    INVALID_NUMBER_INPUT,
    INVALID_NUMBERS_INPUT,
    INVALID_PURCHASE_COUNT,
    INVALID_LOTTO_NUMBER_RANGE,
    INVALID_PURCHASE_AMOUNT,
    COLLECTION_MUST_NOT_BE_EMPTY,
    NOT_UNIQUE_WINNING_NUMBERS,
    NOT_UNIQUE_LOTTO_NUMBERS,
    WINNING_NUMBERS_CONTAIN_BONUS_NUMBER
}
